[book]
title = "COMPSCI 713 Mid-Term Exam Study Guide"
authors = ["BriceLucifer"]
language = "en"
src = "src"

[build]
build-dir = "output"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true

[output.html.fold]
enable = true
level = 1
